### ISSUE TITLE
Publish to Crates.io

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/codespan#10]
This is blocking gluon-lang/gluon#505 and prevents [Piklelet](https://github.com/brendanzab/pikelet) from being published to Crates.io as well. Is there anything blocking us from doing this?

**Comment by brendanzab** [comment]
One thing: I'm not sure about the naming of `codespan-reporting` - should we name it something like `codespan-reporting-cli`, seeing as we are hoping to add LSP and JS editor support in the future… 🤔

**Comment by Marwes** [comment]
> One thing: I'm not sure about the naming of codespan-reporting - should we name it something like codespan-reporting-cli, seeing as we are hoping to add LSP and JS editor support in the future… 🤔

I think it is only worthwhile to split up now if we expect that, LSP and JS editors need different dependencies than cli (-termcolor I guess) and the current `Diagnostic` struct is not useful for those backends. Otherwise the crate is either small enough that it is not a big deal to have multiple backends in one or we can split it up later into `codespan-reporting` + `codespan-reporting-cli` and keep `Diagnostic` in the former crate.

**Comment by Marwes** [comment]
Otherwise there isn't anything blocking it.
