### ISSUE TITLE
Indexing with `ByteIndex`

### ISSUE THREAD

**Issue by Laegluin** [brendanzab/codespan#46]
If I'm not mistaken, `ByteIndex` uses 1-based indexing, but that is never mentioned in the docs. This should probably be documented, since I would have expected it to be 0-based.

I'd happily submit a PR with some changes :)

**Comment by brendanzab** [comment]
This is because of how we don't have a separate 'file id' to differentiate files in the filemap. the '0' index is intended to denote positions that don't correspond to any file. I realize that this is confusing though! As mentioned in #52, the language-reporting crate simplifies this way of doing things greatly, by instead just going with a separate file id.

**Comment by Laegluin** [comment]
Definitely makes more sense in that case, I'm not sure how I even managed to miss `ByteIndex::none` to begin with.

**Comment by Laegluin** [comment]
Closed by #54.
