### ISSUE TITLE
Use another identifier than 'Label'

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/codespan#95]
`Label` is a pretty common term in programming languages, and one that I currently conflict with! Instead In need to do:

```rust
use codespan_reporting::Label as DiagnosticLabel;
```

Some ways to fix this could be to:

- Use a different identifier, like `Note`.
- Use a type alias instead, ie: 
  ```rust
  type Label = (FileId, Span, String);
  ```

Thoughts?

**Comment by Johann150** [comment]
1. Renaming the `struct` would be a quite serious breaking change that would affect pretty much all use cases.
2. Using the type alias would be an even worse breaking change because type aliases cannot be `impl`ed, thus creating a label would have to be changed from say
    ```Rust
    Label::primary(file, from..to).with_message("blah")
    ```
    to 
    ```Rust
    (LabelStyle::Primary, file, from..to, String::from("blah"))
    ```
    which arguably is less readable. Another problem with this approach may be that the text type is no longer an `Into<String>`, necessitating either a `String::from` or an `into()` making it even less readable.

This leads me to the conclusion that changing the `struct`s name is the best solution out of the two. But I don't think that this is actually a big problem. After all you could also just do:

```Rust
use codespan_reporting::diagnostics;
use crate::own_stuff; // or whatever
// ...
own_stuff::Label( /* do stuff */ )
// ...
diagnostics::Diagnostic::error().with_labels(vec![
    diagnostics::Label::primary(file, from..to).with_message("syntax error"),
])
```

**Comment by brendanzab** [comment]
Yeah, I don't think this is a massive issue. Let's close this for now!

Anyone else feel free to chime in though if you disagree!
